# Generated by Django 2.2.3 on 2019-11-25 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('school', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('notification_type', models.CharField(max_length=10)),
                ('areas_of_expertise', models.TextField(blank=True)),
                ('past_accomplishments', models.TextField(blank=True)),
                ('github_link', models.CharField(blank=True, max_length=50)),
                ('linkedin_link', models.CharField(blank=True, max_length=50)),
                ('personal_website_link', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('looking_to_join', models.BooleanField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('communication', models.IntegerField(blank=True)),
                ('public_speaking', models.IntegerField(blank=True)),
                ('teamwork', models.IntegerField(blank=True)),
                ('leadership', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
