# Generated by Django 2.2.3 on 2019-11-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarhacks', '0007_auto_20191125_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
