# Generated by Django 2.2.3 on 2019-11-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarhacks', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
