# Generated by Django 2.2.3 on 2019-11-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarhacks', '0014_notification_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
