# Generated by Django 2.2.3 on 2019-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarhacks', '0016_auto_20191126_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
