# Generated by Django 2.2.3 on 2019-11-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarhacks', '0017_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='looking_to_join',
        ),
    ]
