# Generated by Django 2.2.3 on 2019-11-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarhacks', '0018_remove_userprofile_looking_to_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_type',
        ),
    ]
