# Generated by Django 2.2.3 on 2019-11-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhacks', '0004_auto_20191125_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
