# Generated by Django 2.2.3 on 2019-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhacks', '0009_auto_20191126_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
