# Generated by Django 2.2.3 on 2019-11-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhacks', '0011_auto_20191126_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
