# Generated by Django 2.2.3 on 2019-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhacks', '0020_remove_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
