# Generated by Django 2.2.3 on 2019-11-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testhacks', '0021_team_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='school',
            new_name='title',
        ),
    ]
