# Generated by Django 2.2.3 on 2019-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamIdentification',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
