# Generated by Django 2.2.3 on 2019-12-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_teamidentification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamIdentification',
        ),
    ]
