# Generated by Django 2.2.3 on 2019-12-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20191202_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='source_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
