# Generated by Django 2.2.3 on 2019-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20191202_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
            ],
        ),
    ]
