# Generated by Django 2.2.3 on 2019-12-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_teamidentification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=20)),
                ('team_id', models.CharField(max_length=15)),
                ('submission_name', models.CharField(max_length=50)),
                ('submission_description', models.TextField()),
            ],
        ),
    ]
