# Generated by Django 2.2.3 on 2019-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_award_hackathon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='team_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
