# Generated by Django 2.2.3 on 2019-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_auto_20191203_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='prize',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
