# Generated by Django 2.2.3 on 2019-12-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_award_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
